# Generated by Django 3.2.8 on 2021-11-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTopVideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fecha',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
